#ifndef VIRTIO_GENERIC_H_
#define VIRTIO_GENERIC_H_

#define RESET 0x0
#define DEVICE_ACK 0x1
#define DRIVER_LOADED 0x2
#define DRIVER_READY 0x4
#define FEATURES_OK 0x8
#define DEVICE_ERROR 0x40
#define DRIVER_FAILED 0x80

#define VIRTIO_PCI_CAP_COMMON_CFG 1
#define VIRTIO_PCI_CAP_NOTIFY_CFG 2
#define VIRTIO_PCI_CAP_ISR_CFG 3
#define VIRTIO_PCI_CAP_DEVICE_CFG 4

#endif