[build]
target = "aarch64-unknown-none"
rustflags = ["-C", "target-feature=-fp-armv8,-neon"]

# [unstable]
# build-std = ["core", "compiler_builtins"]

# [target.armv7a-none-eabi]
# rustflags = ["-C", "link-arg=--emit=obj"]